shp_column_name: BEZEICH
targets:
  -
    db:
      dbname: standortsuche
    table_name: ortsteil
    column_name: geom
  -
    db:
      dbname: klarschiff_backend
    table_name: klarschiff_stadtteil_grenze
    column_name: grenze
